{% set version = "2.46.0-0" %}

package:
  name: aqua
  version: {{ version }}

source:
  url: https://github.com/aquaproj/aqua/archive/v{{ version }}.tar.gz
  sha256: d508b806c8a0cbd2f2c13b3443ef38e19de970d2243c7ee58a8e41b06e240837

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - aqua --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Declarative CLI Version manager written in Go. Support Lazy Install, Registry, and continuous update with Renovate. CLI version is switched seamlessly
  home: https://github.com/aquaproj/aqua
  dev_url: https://github.com/aquaproj/aqua

extra:
  recipe-maintainers:
    - danielnachun
