{% set version = "2.55.0-1" %}

package:
  name: aqua
  version: {{ version | replace('-', '_') }}

source:
  url: https://github.com/aquaproj/aqua/archive/v{{ version }}.tar.gz
  sha256: f20fd4b1e2e031404df32f8eaa1401635b6b53436d5a25d1fc6a8eeea6ef1885

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - aqua --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Declarative CLI Version manager written in Go. Support Lazy Install, Registry, and continuous update with Renovate. CLI version is switched seamlessly
  home: https://github.com/aquaproj/aqua
  dev_url: https://github.com/aquaproj/aqua

extra:
  recipe-maintainers:
    - danielnachun
