schema_version: 1

context:
  version: "2.59.2-0"

package:
  name: aqua
  version: ${{ version | replace('-', '_') }}

source:
  url: https://github.com/aquaproj/aqua/archive/v${{ version }}.tar.gz
  sha256: f7f562d7d3640ecb9a1905b5c0f8284c360c007b4d51fd9336f02af5df869c94

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - aqua --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Declarative CLI Version manager written in Go. Support Lazy Install, Registry, and continuous update with Renovate. CLI version is switched seamlessly
  homepage: https://github.com/aquaproj/aqua
  repository: https://github.com/aquaproj/aqua

extra:
  recipe-maintainers:
    - danielnachun
