schema_version: 1

context:
  version: "2.56.3"

package:
  name: aqua
  version: ${{ version | replace('-', '_') }}

source:
  url: https://github.com/aquaproj/aqua/archive/v${{ version }}.tar.gz
  sha256: bf807dd91a3e2194de26da1c42842e7ba55bcd0be5a33f4a8f46a2f283a5aa86

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - aqua --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Declarative CLI Version manager written in Go. Support Lazy Install, Registry, and continuous update with Renovate. CLI version is switched seamlessly
  homepage: https://github.com/aquaproj/aqua
  repository: https://github.com/aquaproj/aqua

extra:
  recipe-maintainers:
    - danielnachun
