schema_version: 1

context:
  version: "2.56.0"

package:
  name: aqua
  version: ${{ version | replace('-', '_') }}

source:
  url: https://github.com/aquaproj/aqua/archive/v${{ version }}.tar.gz
  sha256: 5c6926f50150517ad3c8931921a2bf8f0d5c8947a81a14b7582ca4a1b4e118a2

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - aqua --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Declarative CLI Version manager written in Go. Support Lazy Install, Registry, and continuous update with Renovate. CLI version is switched seamlessly
  homepage: https://github.com/aquaproj/aqua
  repository: https://github.com/aquaproj/aqua

extra:
  recipe-maintainers:
    - danielnachun
