schema_version: 1

context:
  version: "2.60.0"

package:
  name: aqua
  version: ${{ version | replace('-', '_') }}

source:
  url: https://github.com/aquaproj/aqua/archive/v${{ version }}.tar.gz
  sha256: 7678e31d3daedab8e869695c1862f448b94d8257d3657e5b49dbe6274174a540

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - aqua --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Declarative CLI Version manager written in Go. Support Lazy Install, Registry, and continuous update with Renovate. CLI version is switched seamlessly
  homepage: https://github.com/aquaproj/aqua
  repository: https://github.com/aquaproj/aqua

extra:
  recipe-maintainers:
    - danielnachun
